sudo: required
dist: trusty

branches:  
  only:
    - master

addons:
  chrome: stable

language: node_js
node_js:
  - "12"

services:
  - docker

before_script:
  - npm install -g @angular/cli

script:
  - ng build --prod --aot
  - ng test

after_success:
  - docker build -t straubwa/lego-part-tracker-ui -f ./.docker/nginx.dockerfile .
  - docker tag straubwa/lego-part-tracker-ui straubwa/lego-part-tracker-ui:$(git rev-parse --short HEAD)
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push straubwa/lego-part-tracker-ui
