sudo: required
dist: trusty

branches:  
  only:
    - master

addons:
  chrome: stable

language: node_js
node_js:
  - "8.10"

before_script:
  - npm install -g @angular/cli

script:
  - ng build --prod --aot
  - ng test

before_deploy:
  - cd dist

deploy:
  provider: azure_web_apps
  skip_cleanup: true
  verbose: true
  site: BrickTracker